kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  # namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  {{- with .Values.container }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
  template:
    metadata:
      name: {{ $.Release.Name }}
      labels:
        app: {{ $.Release.Name }}
    spec:
      containers:
      - name: {{ $.Release.Name }}
        image: {{ $.Values.image}}
        args:
          {{- range .args }}
          - {{ . | quote }}
          {{- end }}
        {{- if eq .livenessProbe.enabled true }}
        livenessProbe:
          {{- if eq .livenessProbe.httpGet.enabled true }}
          httpGet:
            path: {{ .livenessProbe.httpGet.path }}
            port: {{ .livenessProbe.httpGet.port }}
          {{- end }}
          initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .livenessProbe.periodSeconds }}
          failureThreshold: {{ .livenessProbe.failureThreshold }}
        {{- end }}
        {{- if eq .readinessProbe.enabled true }}
        readinessProbe:
          {{- if eq .readinessProbe.httpGet.enabled true }}
          httpGet:
            path: {{ .readinessProbe.httpGet.path }}
            port: {{ .readinessProbe.httpGet.port }}
          {{- end }}
          initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .readinessProbe.periodSeconds }}
          successThreshold: {{ .readinessProbe.successThreshold }}
          failureThreshold: {{ .readinessProbe.failureThreshold }}
        {{- end }}
        ports:
        {{- range .ports }}
        - name: {{ .name }}
          containerPort: {{ .containerPort }}
        {{- end }}
        {{- if eq .resources.enabled true }}
        resources:
          limits:
            cpu: {{ .resources.limits.cpu }}
            memory: {{ .resources.limits.memory }}
        {{- end }}
    {{- end }}