container:
  args:
  replicas: 2
  livenessProbe:
    enabled: false
    httpGet:
      enabled: false
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    enabled: false
    httpGet:
      enabled: false
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 3
    failureThreshold: 3
  ports:
    - name: http
      containerPort: 80
  resources:
    enabled: true
    limits:
      cpu: 250m
      memory: 32Mi
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
service:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 80
      port: 80

# namespace: ms-app

image:
  deividdua32/imc