container:
  args:
  replicas: 1
  livenessProbe:
    enabled: false
    httpGet:
      enabled: false
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    enabled: false
    httpGet:
      enabled: false
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 3
    failureThreshold: 3
  ports:
    - name: http
      containerPort: 80
  resources:
    enabled: true
    limits:
      cpu: 200m
      memory: 128Mi
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
service:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 80
      port: 80
ingress:
  host: "app.teste.nip.io"
  backend:
    serviceName: "svc-new-comments"
    servicePort: 80

image:
  deividdua32/api-comments:v1